### ISSUE TITLE
Script editor shows incorrect errors during code verification

### ISSUE THREAD

**Issue by mifrey00** [calaos/calaos_installer#33]
Script editor shows _"Error Runtime error : [string "CalaosScript"]:18: attempt to concatenate a boolean value"_ with the code `print("Timer = " .. calaos:getInputValue(timer_id))` although `calaos:getInputValue(timer_id)` returns a string if timer_id is an InputTimer object.

A temporary workaround is to use `tostring(calaos:getInputValue(timer_id)))` so that Calaos Installer accepts the script.

Version: calaos_installer_setup_v2.0-beta3-0-g979782f.exe

**Comment by raoulh** [comment]
Fixed in https://github.com/calaos/calaos_installer/commit/5ef15d7445ab3a5306c0c12cb4c6064eb6f57514

Thanks
