### ISSUE TITLE
calaos installer 3.3 losing some datas in action touchscreen

### ISSUE THREAD

**Issue by azertybepo** [calaos/calaos_installer#45]
When using action touchscreen, data is not retrieved from rules.xml correctly after restarting calaos_installer.

Camera to display on screen is empty after restart of calaos_installer and the data is missing in rules.xml
`        <calaos:action type="touchscreen" action="view_camera" camera=""/>
`

**Comment by raoulh** [comment]
calaos_installer v3.5 released: https://calaos.fr/download/experimental/calaos_installer/
